### ISSUE TITLE
Detect repositories with a high numbers of outstanding vulnerability reports

### ISSUE THREAD

**Issue by hwine** [mozilla-services/GitHub-Audit#46]
"High numbers" is quite subjective, so will need to be configurable.

**Comment by g-k** [comment]
This is available through the GH graphql API with a preview content type: https://developer.github.com/v4/object/repositoryvulnerabilityalert/

I have a script for scrapping this information in https://github.com/mozilla-services/find-package-rugaru/

**Comment by hwine** [comment]
Great - I knew about the API, but didn't have any GraphQL tooling yet. the "no API" is overloaded as "lots of work" :D  I'll still leave here, as it is a new pytest-services directory.

**Comment by hwine** [comment]
This is handled via baseline report. No action needed here.
